### PR TITLE
remove Werror to make project build

### PR DESCRIPTION
**Pull request by Ecordonnier**
The project is failing to compile with gcc because of unused parameters warnings and mising field initializers warnings.

### CODE REVIEW

**Comment by bvanassche** [comment]
That's unexpected. I don't see these warnings on my setup. Which version of the Net-SNMP headers are you using and what is the origin of these headers (Linux distro or Net-SNMP installed from source)?

**Comment by bvanassche** [comment]
Please note that I didn't want to close this pull request. That was an unintended side effect of a git push.

**Comment by Ecordonnier** [comment]
Sorry, I had completely forgotten about this. When I try to compile the project, this is what I get (as you can see the errors are unrelated to the headers):

> cordonni@etiennepc:~/repos/subagent-example$ make
> gcc `net-snmp-config --cflags` -Wall -Wextra -Werror   -c -o example-demon.o example-demon.c
> example-demon.c: In function ‘stop_server’:
> example-demon.c:11:17: error: unused parameter ‘a’ [-Werror=unused-parameter]
>  stop_server(int a) {
>                  ^
> example-demon.c: In function ‘main’:
> example-demon.c:16:11: error: unused parameter ‘argc’ [-Werror=unused-parameter]
>  main (int argc, char **argv) {
>            ^~~~
> example-demon.c:16:24: error: unused parameter ‘argv’ [-Werror=unused-parameter]
>  main (int argc, char **argv) {
>                         ^~~~
> cc1: all warnings being treated as errors
> <builtin>: recipe for target 'example-demon.o' failed
> make: *** [example-demon.o] Error 1


My environment is debian 9:
```
$ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

```

**Comment by Ecordonnier** [comment]
Did you have the time to check my last comment?

**Pull request closed without merging**
